language: python
addons:
  apt:
    packages:
    - time

matrix:
  include:
    - python: "2.7"
      env: FEATURES=[openstack,ec2,daemon]
    - python: "2.6"
      env: FEATURES=

install:
  - "pip install --upgrade setuptools pip"
  - "pip install 'pytest==3.2.5' mock"
  - "pip install -e .$FEATURES"

script:
  - export BOTO_CONFIG=/dev/null
  - pytest -v
