language: python

addons:
  apt:
    packages:
    - time

# installing `cffi` (required by some dependency of `paramiko`) on
# Python 2.6 requires that `pycparser` is *already* installed on the
# system, otherwise the latest version will be unconditionally
# downloaded and installed, so we need to install it in a separate
# step *before* installation of the main code... hance the `$PRE`
# environment variable.
install:
  - "pip install --upgrade setuptools pip"
  - 'if [ -n "$PRE" ]; then pip install $PRE; fi'
  - 'pip install mock "pytest>=4.1" "pytest-cov<2.6" pytest-coverage codecov'
  - "pip install -e .$FEATURES"

script:
  - export BOTO_CONFIG=/dev/null
  - pytest -v --cov=gc3libs --cov-branch

matrix:
  include:
    - python: "2.7"
      env:
        - FEATURES="[openstack,ec2,daemon]"
        - PRE=""
    - python: "2.6"
      env:
        - FEATURES=""
        # `inotifyx` is required otherwise collection of tests errors out
        - PRE="inotifyx numpy<1.12 pycparser<2.19 pytest==3.2.5"
        - PYTEST_ADDOPTS="--ignore gc3libs/backends/ec2.py --ignore gc3libs/backends/tests/test_ec2.py"
    - python: "3.5"
      env:
        - FEATURES="[openstack,ec2,daemon]"
        - PRE=""
        - GC3PIE_FORCE_INSTALL="yes"
    - python: "3.6"
      env:
        - FEATURES="[openstack,ec2,daemon]"
        - PRE=""
        - GC3PIE_FORCE_INSTALL="yes"
    - python: "3.7"
      env:
        - FEATURES="[openstack,ec2,daemon]"
        - PRE=""
        - GC3PIE_FORCE_INSTALL="yes"

  allow_failures:
    - python: '2.6'
    - python: '3.5'
    - python: '3.6'
    - python: '3.7'

after_success:
  # publish code coverage data to http://codecov.io/gh/uzh/gc3pie
  - codecov
