language: python

addons:
  apt:
    packages:
    - time

# installing `cffi` (required by some dependency of `paramiko`) on
# Python 2.6 requires that `pycparser` is *already* installed on the
# system, otherwise the latest version will be unconditionally
# downloaded and installed, so we need to install it in a separate
# step *before* installation of the main code... hance the `$PRE`
# environment variable.
install:
  - "pip install --upgrade setuptools pip"
  - 'if [ -n "$PRE" ]; then pip install $PRE; fi'
  - 'pip install pytest mock'
  - "pip install -e .$FEATURES"

script:
  - export BOTO_CONFIG=/dev/null
  - pytest -v --continue-on-collection-errors

matrix:
  include:
    - python: "2.7"
      env:
        - FEATURES="[openstack,ec2,daemon]"
        - PRE=""
    - python: "2.6"
      env:
        - FEATURES=""
        - PRE="'numpy<1.12' 'pycparser<2.19' 'pytest==3.2.5'"
